apiVersion: apps/v1
kind: Deployment
metadata:
  name: studio-lights
  namespace: studio-lights
  labels:
    app: studio-lights
spec:
  replicas: 1
  selector:
    matchLabels:
      app: studio-lights
  template:
    metadata:
      labels:
        app: studio-lights
    spec:
      containers:
      - name: lights
        image: nullchannel/lights:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: lights-service
  namespace: studio-lights
spec:
  type: NodePort
  selector:
    app: studio-lights
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 32001
